### ISSUE TITLE
AddIn for xUnit

### ISSUE THREAD

**Issue by ZwapKillrath** [Inflectra/spira-nunit#1]
Have you made one for xUnit as well? If not, what are the steps to convert this solution to achieve that?

**Comment by yipmarvel** [comment]
We do not have an xUnit addin. You can view all available unit test integrations on our [downloads page](https://www.inflectra.com/SpiraPlan/Downloads.aspx#TestAutomation). You are welcome to fork this repo to get it to work with xUnit if. you like. We cannot provide support or advice about how to do that I am afraid.
